' SolidWorks Macro: Motor_Mount
' Generated by text-to-cad | Template: motor_mount
' Late-bound VBA -- all Object types + minimal API params
' Usage: Alt+F11 -> File -> Import File -> select this .bas -> F5

Dim swApp As Object
Dim swModel As Object
Dim sketchMgr As Object
Dim featMgr As Object

Sub main()
    Set swApp = Application.SldWorks
    Set swModel = swApp.NewPart
    Set sketchMgr = swModel.SketchManager
    Set featMgr = swModel.FeatureManager
    
    ' Motor Mount D=52mm
    Call swModel.Extension.SelectByID2("上视基准面", "PLANE", 0, 0, 0, False, 0, Nothing)
    sketchMgr.InsertSketch True
    sketchMgr.CreateCircleByRadius 0, 0, 0, 0.02600000000
    featMgr.FeatureExtrusion2 True, False, False, 0, 0, 0.005000000000, 0.005000000000, False, False, False, False, 0, 0, False, False, False, False, True, True, True, 0, 0, False
    swModel.ClearSelection2 True
    Call swModel.Extension.SelectByID2("", "FACE", 0, 0, 0.005000000000, False, 0, Nothing)
    sketchMgr.InsertSketch True
    sketchMgr.CreateCircleByRadius 0, 0, 0, 0.006000000000
    featMgr.FeatureCut True, False, False, 0, 0, 0.01500000000, 0.01500000000, False, False, False, False, 0.0, 0.0, 0.0, 0.0, False, False, False, True, True
    swModel.ClearSelection2 True
    Call swModel.Extension.SelectByID2("", "FACE", Cos(0.0) * (0.01600000000), Sin(0.0) * (0.01600000000), 0.005000000000, False, 0, Nothing)
    sketchMgr.InsertSketch True
    sketchMgr.CreateCircleByRadius 0, 0, 0, 0.001600000000
    featMgr.FeatureCut True, False, False, 0, 0, 0.01500000000, 0.01500000000, False, False, False, False, 0.0, 0.0, 0.0, 0.0, False, False, False, True, True
    swModel.ClearSelection2 True
    Call swModel.Extension.SelectByID2("", "FACE", Cos(1.5707963267948966) * (0.01600000000), Sin(1.5707963267948966) * (0.01600000000), 0.005000000000, False, 0, Nothing)
    sketchMgr.InsertSketch True
    sketchMgr.CreateCircleByRadius 0, 0, 0, 0.001600000000
    featMgr.FeatureCut True, False, False, 0, 0, 0.01500000000, 0.01500000000, False, False, False, False, 0.0, 0.0, 0.0, 0.0, False, False, False, True, True
    swModel.ClearSelection2 True
    Call swModel.Extension.SelectByID2("", "FACE", Cos(3.141592653589793) * (0.01600000000), Sin(3.141592653589793) * (0.01600000000), 0.005000000000, False, 0, Nothing)
    sketchMgr.InsertSketch True
    sketchMgr.CreateCircleByRadius 0, 0, 0, 0.001600000000
    featMgr.FeatureCut True, False, False, 0, 0, 0.01500000000, 0.01500000000, False, False, False, False, 0.0, 0.0, 0.0, 0.0, False, False, False, True, True
    swModel.ClearSelection2 True
    Call swModel.Extension.SelectByID2("", "FACE", Cos(4.71238898038469) * (0.01600000000), Sin(4.71238898038469) * (0.01600000000), 0.005000000000, False, 0, Nothing)
    sketchMgr.InsertSketch True
    sketchMgr.CreateCircleByRadius 0, 0, 0, 0.001600000000
    featMgr.FeatureCut True, False, False, 0, 0, 0.01500000000, 0.01500000000, False, False, False, False, 0.0, 0.0, 0.0, 0.0, False, False, False, True, True
    swModel.ClearSelection2 True
    swModel.ViewZoomtofit2
    Set featMgr = Nothing
    Set sketchMgr = Nothing
    Set swModel = Nothing
    Set swApp = Nothing
End Sub